#!/usr/bin/env sh

echo "Hi! Setting up mcsn_supervisor!"

# Ensure that Python is installed as expected by the application.
echo "> Ensuring asdf can manage Python"
asdf plugin-add python
echo "> Installing Python requirements"
asdf install
echo "> Reshimming..."
asdf reshim python

# Set up the working environment
echo "> Creating virtualenv for mcsn_supervisor"
python -m venv ./.venv --prompt mcsn_supervisor
echo "> Activating virtualenv"
. ./.venv/bin/activate
echo "> Getting pip up to date"
pip install --upgrade pip
echo "> Installing dependencies"
pip install -r requirements.txt
echo "> Leaving virtualenv"
deactivate

echo ""
echo "mcsn_supervisor is ready to use!"
echo "NOTE: this script is idempotent. If any step failed,"
echo "you can safely re-run this command to try again"
