.container
  .row
    .col-sm-10
      .page-header
        h1 Admin Dashboard

      h2 Submissions

      ul
        li
          a(href="/admin/submissions") Manage Submissions
        li
          a(href="/admin/submissions/runners") Runner Submissions Table


      h2 Account management

      ul
        li
          a(href="/admin/accounts") View accounts


      h2 Ops

      ul
        li
          a(href="/admin/feature_flags") Manage Feature Flags
